version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME}
    volumes:
      - ./mysql:/var/lib/mysql # persist sql data
    restart: always

networks:
  default:
    external:
      name: ${PROXY_NAME}
